### ISSUE TITLE
Working directory defaults to IntelliJ path, should be set to project directory

### ISSUE THREAD

**Issue by mduggan** [mjedynak/pit-idea-plugin#26]
I often write tests that load reference data from some sub-directory of the project, eg:
```java
public class TestLoadingFile {
  @Test
  public void testFileLoad() {
    final File jsonFile = new File("test/resources/reference_data.json");
    Assert.assertTrue(jsonFile.exists());
  }
}
```
If the file is there, this test will succeed from the commandline, from IntelliJ, and will work with pitest from the commandline, but when run from the pit IDEA plugin, it fails and says "Mutation testing requires a green suite".

The reason for this is that the working directory of the JVM is not configured, so it defaults to the IntelliJ directory.  The simple fix is to set the working directory first.

**Comment by pescadorbob** [comment]
I am encountering a similar issue as you had from this where the working directory wasn't set correctly. In my case though, I have a multi-module project, and when I run pitest on a submodule that references a file needed for tests, it can't find it because the file is specified relative to the base dir of the sub project module, not to the whole project. 

I am thinking of a contribution where the 'working dir' is added to the plugin so that a user can specify the base working directory where the tests should be run from to resolve this. Sound OK?
